### ISSUE TITLE
GitHub Actions workflow updates: 2023.05.22

### ISSUE THREAD

**Issue by obervinov** [obervinov/vault-package#24]
- [ ] Add a filter to the release creation workflow to exclude the launch if the module files have not changed
```yml
name: Create GitHub Release

on:
  push:
    branches: [main]
    paths: ['users/**']

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.4
```

- [ ] Add workflow with package installation verification (by tag, branch, default)
```yml
  verify-package:
    uses: obervinov/_templates/.github/workflows/verify.package.yml@v1.0.4
```

- [ ] Tests and checks workflow - run on the main branch for the show badge
```yml
name: Tests and Checks

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'
```
